sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ***REMOVED***
#自定义阿里云OSS的配置信息
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    accessKeyId: ***REMOVED***
    accessKeySecret: REPLACED
    bucketName: web-tlias-demo66